version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: meridian
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d gaming -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://postgres:5432/meridian -schemas=public -user=postgres -password=password migrate
    volumes:
      - ./.docker/flyway/:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  meridian:
    container_name: meridian
    build: .
    environment:
      PG_HOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      flyway:
        condition: service_completed_successfully

volumes:
  postgres:
    driver: local
